# Generated by Django 4.2.8 on 2023-12-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEkstraksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, null=True)),
                ('nama_img', models.CharField(max_length=256, null=True)),
                ('host_img', models.FileField(upload_to='extracts/')),
                ('ukuran', models.CharField(max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extract_id', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPenyisipan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, null=True)),
                ('nama_img', models.CharField(max_length=256, null=True)),
                ('host_img', models.ImageField(upload_to='embeds/')),
                ('wm_img', models.ImageField(upload_to='watermark/')),
                ('result', models.ImageField(blank=True, null=True, upload_to='result/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('psnr', models.FloatField(null=True)),
                ('mse', models.FloatField(null=True)),
                ('embed_id', models.SlugField(null=True)),
            ],
        ),
    ]
