# Generated by Django 4.2.8 on 2023-12-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelEkstraksi',
            new_name='ModelPengekstrakan',
        ),
    ]
